# Generated by Django 5.1.1 on 2024-09-17 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_educationinquiry_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinquiry',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employmentinquiry',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
