# Generated by Django 5.1.1 on 2024-09-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_educationinquiry_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='educationinquiry',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='employmentinquiry',
            name='submitted_at',
        ),
    ]
